"""Fixes bugs in seed.py

Revision ID: 62c7c74b3187
Revises: 10cd385267c0
Create Date: 2023-10-06 17:55:04.170786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c7c74b3187'
down_revision = '10cd385267c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post_to_category',
    sa.Column('blog_post_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_post.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_post_to_category')
    # ### end Alembic commands ###
